### ISSUE TITLE
There is an error that makes this unusable

### ISSUE THREAD

**Issue by jlnhlfan** [jankammerath/HttpTimeTravelProxy#1]
![Screenshot_May_20_2022_01_02_20_PM](https://user-images.githubusercontent.com/31529087/169602780-e54b588e-0d7c-4eb7-a9fb-6307858e6a13.png)

This WOULD be useful for me to look at the NHL's website circa 1999... if there wasn't an error, which there is. It's a syntax error on line 16, character 1 (which is the "c" in "const".  Is there any way around this so that it can actually work, for am I screwed?

**Comment by ghost** [comment]
Just use web.archive.org

**Comment by jankammerath** [comment]
This application is a daemon built to run on Linux/BSD with systemd. Stop using GitHub as a software repository please. It’s not.
